sudo: required
services: docker

before_install:
 - docker pull jfloff/lineageos

script:
 - mkdir $HOME/.android
 - mkdir -p ${TRAVIS_BUILD_DIR}/Lineage/
 
 docker run --rm --privileged -v "${TRAVIS_BUILD_DIR}/Lineage/":/home/lineageos --env-file h990.env -ti jfloff/lineageos lineageos init build
