sudo: required
services: docker

before_install:
 - docker pull marceloneil/docker-lineageos

script:
 - mkdir $HOME/.android
 - mkdir -p ${TRAVIS_BUILD_DIR}/Lineage/ && cd ${TRAVIS_BUILD_DIR}/Lineage/
 - mkdir -p ${TRAVIS_BUILD_DIR}/ccache/
 - mkdir -p ${TRAVIS_BUILD_DIR}/zips/
 - mkdir -p ${TRAVIS_BUILD_DIR}/android-certs/

 - docker pull marceloneil/docker-lineageos
 
 - docker run  --rm -v ${TRAVIS_BUILD_DIR}/ccache:/srv/ccache -v ${TRAVIS_BUILD_DIR}/Lineage:/build/android -v ${TRAVIS_BUILD_DIR}/zips:/build/zips -v ${TRAVIS_BUILD_DIR}/android-certs:/build/android-certs marceloneil/docker-lineageos migration


 - docker run -d --name lineageos-build -e DEVICE_LIST="h990" -e NAME="João Victor" -e EMAIL="joaovictor.rodsouza@gmail.com" -v ${TRAVIS_BUILD_DIR}/ccache:/srv/ccache -v ${TRAVIS_BUILD_DIR}/Lineage:/build/android -v ${TRAVIS_BUILD_DIR}/zips:/build/zips -v - mkdir -p ${TRAVIS_BUILD_DIR}/android-certs:/build/android-certs marceloneil/docker-lineageos 

 - docker start lineageos-build to rebuild

after_success:
 - export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm")
 - cd ${TRAVIS_BUILD_DIR}/zips/ &&  zip jvlineage * .* &&  curl --upload-file ./jvlineage.zip https://transfer.sh/jvlineage-${TRAVIS_CURRENT_DATE}.zip
  
